"""adding comments table

Revision ID: 359cbaa3e43d
Revises: 6987519e7ad1
Create Date: 2023-02-08 17:06:14.368226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359cbaa3e43d'
down_revision = '6987519e7ad1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
